apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-appmesh-inject.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "aws-appmesh-inject.name" . }}
    helm.sh/chart: {{ include "aws-appmesh-inject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "aws-appmesh-inject.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-appmesh-inject.name" . }}
    helm.sh/chart: {{ include "aws-appmesh-inject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "aws-appmesh-inject.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-appmesh-inject.name" . }}
    helm.sh/chart: {{ include "aws-appmesh-inject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-appmesh-inject.name" . }}
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "aws-appmesh-inject.name" . }}
  apiGroup: ""
