apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-appmesh-inject.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "aws-appmesh-inject.name" . }}
    helm.sh/chart: {{ include "aws-appmesh-inject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "aws-appmesh-inject.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
